plugins:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rbs_inline

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

require:
  - ./lib/rubocop/cop/custom/restrict_params_access.rb

Custom/RestrictParamsAccess:
  Enabled: true
  Include:
    - 'app/controllers/**/*.rb'

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 200
Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
Metrics/ClassLength:
  Max: 300
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Max: 15

Layout/LineLength:
  Max: 150
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
Layout/AssignmentIndentation:
  Enabled: true
Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'
Lint/RescueException:
  Enabled: false
Lint/UnusedMethodArgument:
  Exclude:
    - 'spec/**/*'
Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'
    - 'app/views/**/*'

Naming/MethodParameterName:
  AllowedNames:
    - n
    - x
    - y
    - id
    - to

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - 'lib/**/*'
    - 'config/**/*'
Style/OneClassPerFile:
  Exclude:
    - 'config/initializers/**/*'
Style/AccessorGrouping:
  EnforcedStyle: separated
Style/RbsInline:
  Include:
    - 'app/**/*'
    - 'lib/**/*'
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
Style/ArgumentsForwarding:
  Enabled: false

Rails:
  Exclude:
    - 'bin/*'
Rails/I18nLocaleTexts:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: true
Rails/Exit:
  Exclude:
    - 'spec/**/*'
Rails/OutputSafety:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
