require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/custom_agents", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # CustomAgent. As you add validations to CustomAgent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CustomAgent.create! valid_attributes
      get custom_agents_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      custom_agent = CustomAgent.create! valid_attributes
      get custom_agent_url(custom_agent)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_custom_agent_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      custom_agent = CustomAgent.create! valid_attributes
      get edit_custom_agent_url(custom_agent)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CustomAgent" do
        expect {
          post custom_agents_url, params: { custom_agent: valid_attributes }
        }.to change(CustomAgent, :count).by(1)
      end

      it "redirects to the created custom_agent" do
        post custom_agents_url, params: { custom_agent: valid_attributes }
        expect(response).to redirect_to(custom_agent_url(CustomAgent.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CustomAgent" do
        expect {
          post custom_agents_url, params: { custom_agent: invalid_attributes }
        }.to change(CustomAgent, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post custom_agents_url, params: { custom_agent: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested custom_agent" do
        custom_agent = CustomAgent.create! valid_attributes
        patch custom_agent_url(custom_agent), params: { custom_agent: new_attributes }
        custom_agent.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the custom_agent" do
        custom_agent = CustomAgent.create! valid_attributes
        patch custom_agent_url(custom_agent), params: { custom_agent: new_attributes }
        custom_agent.reload
        expect(response).to redirect_to(custom_agent_url(custom_agent))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        custom_agent = CustomAgent.create! valid_attributes
        patch custom_agent_url(custom_agent), params: { custom_agent: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested custom_agent" do
      custom_agent = CustomAgent.create! valid_attributes
      expect {
        delete custom_agent_url(custom_agent)
      }.to change(CustomAgent, :count).by(-1)
    end

    it "redirects to the custom_agents list" do
      custom_agent = CustomAgent.create! valid_attributes
      delete custom_agent_url(custom_agent)
      expect(response).to redirect_to(custom_agents_url)
    end
  end
end
