plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 200
Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
Metrics/ClassLength:
  Max: 300
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ParameterLists:
  Max: 10

Layout/LineLength:
  Max: 150
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/EmptyBlock:
  Exclude:
    - 'spec/**/*'
Lint/RescueException:
  Enabled: false
Lint/UnusedMethodArgument:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/HashSyntax:
  EnforcedStyle: ruby19

Rails/I18nLocaleTexts:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
