require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 25
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Enabled: true
